language: php

php:
  - 8.2

sudo: false

before_script:
  - cp .env.travis .env
  - phpenv config-rm xdebug.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction

services:
  - memcached
  - redis-server

script:
  - php artisan key:generate
  - vendor/bin/phpunit
