<?php

/*
 * Copyright (C) 2022 - 2025, iDigInfo
 * amast@fsu.edu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

use Illuminate\Support\Str;

/**
 * AutoCache Configuration
 *
 * This configuration file defines the settings for the AutoCache package,
 * which provides automatic caching capabilities for Eloquent models and queries.
 */
return [
    /*
     * Enable or disable AutoCache functionality
     *
     * When set to false, all caching operations will be bypassed
     * and queries will execute normally without caching.
     */
    'enabled' => env('AUTO_CACHE_ENABLED', true),

    /*
     * Cache store to use for AutoCache
     *
     * Specifies which cache driver to use for storing cached data.
     * Supported values: 'redis', 'memcached', 'array', 'file', 'database'
     */
    'store' => env('AUTO_CACHE_STORE', 'redis'),

    /*
     * Default Time To Live (TTL) for cached items
     *
     * The default duration in seconds that cached items will be stored
     * before they expire. Individual cache operations can override this value.
     */
    'ttl' => 3600,

    /*
     * Cache key prefix
     *
     * A prefix that will be prepended to all cache keys generated by AutoCache
     * to avoid conflicts with other cached data in the same store.
     */
    'prefix' => env('AUTO_CACHE_PREFIX', 'auto-cache:').Str::slug(env('APP_NAME', 'laravel'), '-').':',
];
